### ISSUE TITLE
Invalid include headers

### ISSUE THREAD

**Issue by ciulinuwu** [Geometria-Engine/Geometria#4]
Output in Console:
```
"E:\GeometrialHub\Projects\no\no.sln" (default target) (1) ->
"E:\GeometrialHub\Projects\no\Geometria\no.vcxproj" (default target) (2) ->
(ClCompile target) ->
  E:\GeometrialHub\Projects\no\Geometria\Game\GameMain.h(16,73): error C2065: 'randomX': undeclared identifier [E:\Geom
etrialHub\Projects\no\Geometria\no.vcxproj]
  E:\GeometrialHub\Projects\no\Geometria\Game\GameMain.h(16,82): error C2065: 'randomY': undeclared identifier [E:\Geom
etrialHub\Projects\no\Geometria\no.vcxproj]
  E:\GeometrialHub\Projects\no\Geometria\Game\GameMain.h(16,91): error C2065: 'randomZ': undeclared identifier [E:\Geom
etrialHub\Projects\no\Geometria\no.vcxproj]
  E:\GeometrialHub\Projects\no\Geometria\Game\GameMain.h(16,1): error C2661: 'Model::Model': no overloaded function tak
es 3 arguments [E:\GeometrialHub\Projects\no\Geometria\no.vcxproj]
```

Code and IntelliSense error:
```
#pragma once

#include "geometria.h"

struct GameMain
{
    static void Init()
    {
        DrawCall* d = SceneManager::MainScene().CreateDrawCall();

        for(int i = 0; i < 1000; i++)
        {
            // Create a square with a random X, Y and Z positions.
            // The "randomX/Y/Z" are probably going to be floats that get randomized as the for loop goes on.
            Model* model = new Model(Model::Primitives::SQUARE, Vector3(randomX, randomY, randomZ), Vector3(0, 0, 0), Vector3(1, 1, 1));

            // Add a Model to the Draw Call you created earlier.
            RendererCore::AddModel(*model, d->Target());
        }
    }
};
```

```
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (E:\GeometrialHub\Projects\no\Geometria\Game\GameMain.h).C/C++(1696)
cannot open source file "geometria.h"C/C++(1696)
```

Adding full path to the include header results in the same error but for geometria.h's dependencies like "GL/glew.h"

Issue present in:
* 0.2.43

System Information:
* OS: Windows 10

IntelliSense include path:
```
${workspaceFolder}/**
E:/GeometrialHub/Projects/no/Geometria/MainHeader
```

**Comment by TheNachoBIT** [comment]
You're missing the randomX, randomY and randomZ values.

I didn't add them in the documentation because i supposed you'll know how to run random numbers.

This is not an engine bug, its basically a common mistake with beginners in C++

It's fine tho!
If you want to know how to do random numbers, you can take a look at this:
https://cplusplus.com/reference/cstdlib/rand/

or just look up in Google or your favorite search engine: "rand() C++" and you'll get a ton of results! :D

I'm closing this comment since its not a Geometria bug related, but hope it helps :)

**Comment by TheNachoBIT** [comment]
If you want to get the thing quickly, here's the answer:

```c++
int randomX = rand() % 100; // Random number between 0 and 99.
int randomY = rand() % 100; // Random number between 0 and 99.
int randomZ = rand() % 100; // Random number between 0 and 99.
Model* model = new Model(Model::Primitives::SQUARE, Vector3(randomX, randomY, randomZ), Vector3(0, 0, 0), Vector3(1, 1, 1));
```

**Comment by TheNachoBIT** [comment]
Final Message: The compiler screams that you're "including invalid headers" its because C++ compilers tends to yell at you for the wrong reasons.

But in reality, its just something you forgot to add in the code.

Again, hope this helps :)

**Comment by ciulinuwu** [comment]
Ahh. Thank you! Yeah, this is my first time coding in C++ so I don't know much about it x3

**Comment by TheNachoBIT** [comment]
Don't worry!

Everyone's first time is exactly what you're going through, so don't be ashamed, it's completely fine! :D

**Comment by TheNachoBIT** [comment]
I'm going to change the title a bit so other beginners can know how to deal with these type of stuff, if you don't mind.
